### PR TITLE
Add CONFigure:FANx:HYSteresis command (#2)

### PR DESCRIPTION
**Pull request by Zitt**
Allows user to change the hysteresis of a given fan to limit the amount of INFO lines sent to LOG and/or SYSLOG.

### CODE REVIEW

**Comment by tjko** [comment]
Thanks, looks good. I'll just make couple tweaks to keep commands consistent with existing commands (and to behave like other SCPI commands).

**Comment by Zitt** [comment]
@tjko I made even more changes in my fork:
https://github.com/tjko/fanpico/commit/135afb49a38a913e6d1c149c0485899cb9e5fbe0
but I wasn't completely happy with the implementation.

I wanted there to be a HYST sub command (IE see line 2751 in command.c. 
but after spending hours trying to make it work; I realized that you can't have CONF:FANx:HYS:PWM?
because the code isn't structured to "save" the fan index in 
run_cmd()
function. I couldn't make it work. 

As a result; I just flattened the PWM and TACHO hysteresis commands into 
CONFigure:FANx:HYS_Tacho
CONFigure:FANx:HYS_Pwm

IF you'd like me to try a pull request with my changes; please let me know.

**Comment by tjko** [comment]
@Zitt, I noticed same when looking the pull request :) 

Current "prev_cmd" pointer was a "temporary" hack, that I never got around to fix it seems.
I'll see if I can make change to expose the full command "stack" to the command functions in case they're interested other than the previous command in the chain...

**Comment by Zitt** [comment]
Looks like your current commit #108 has the updated changes from my commit.

**Pull request merged**
